[bot]
token = "<discord token here>"
default_prefix = "$"
verbose_errors = false
db_uri = "<postgres database uri>"
extra_cogs = []

[logging]
log_path = "./soundbert.logs"
level = "DEBUG"

[soundboard]
path = "./sounds"